### ISSUE TITLE
Ratelimiting on multiple time units?

### ISSUE THREAD

**Issue by mikehuston** [lyft/ratelimit#107]
We have a use case where we would like to allow a higher number of requests per second and a lower number of requests per minute so that if a user can have request "bursts", but cannot sustain them.

For a concrete example, here is a sample config:
```
domain: mongo_cps
descriptors:
  - key: database
    rate_limit:
      unit: second
      requests_per_unit: 10

  - key: database
    rate_limit:
      unit: minute
      requests_per_unit: 100
```

However, it appears the configuration is fails to load because the time unit is not part of the composite key. That is, we see an error message like

```
error loading new configuration from runtime: my-config.yaml: duplicate descriptor composite key 'mongo_cps.database'
```

Does anyone have workarounds for this or would it be reasonable to include the time unit as part of the composite key if others have similar use cases? Thanks!
