### ISSUE TITLE
How to use this in envoy?

### ISSUE THREAD

**Issue by ggalihpp** [lyft/ratelimit#54]
This is a beginners question, but I can't find any documentation about this, so my configuration so far is like this:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: www.ggalihpp.ga
                  cluster: service_google
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_google
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: minio.ggalihpp.ga
          port_value: 443
    tls_context: { sni: www.minio.ggalihpp.ga }

rate_limit_service:
    grpc_service:
        envoy_grpc:
            cluster_name: service_google
        timeout: 1s
```

How to add limit rps to the `rate_limit_service`?

again, sorry for the beginner question
