### ISSUE TITLE
rate limit service not really block my connection

### ISSUE THREAD

**Issue by jiangytcn** [lyft/ratelimit#59]
Hi, I installed the ratelimit service by docker-compose and created my own configuration file. the service could run up and all works fine, but when I running the benchmark for the service sit behind envoy and ratelimit filter,  the result is not expected,  could you help take a look ?

envoy config
---

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          use_remote_address: true
          server_name: ront-proxy
          stat_prefix: ingress_http
          codec_type: auto
          access_log: # configure logging
            name: envoy.file_access_log
            config:
              path: /dev/stdout
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              rate_limits:
                - stage: 0
                  actions:
                    - remote_address: {}
              routes:
                - match:
                  prefix: "/v1/generic/"
                route:
                  cluster: vault
                  rate_limits:
                    - stage: 0
                      actions:
                        - generic_key: {descriptor_value: "default"}
              - match:
                  prefix: "/v1"
                route:
                  cluster: vault
          http_filters:
          - name: envoy.rate_limit
            config:
              stage: 0
              domain: "ratelimiter"
          - name: envoy.router
            config: {}
  clusters:
  - name: vault
    connect_timeout: 30s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8200
  - name: rate_limit_service
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {} 
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 8081
        
rate_limit_service: 
  grpc_service:
    envoy_grpc:
      cluster_name: rate_limit_service
    timeout: 0.25s
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

retelimit service config
---
```
$ cat examples/ratelimit/config/ratelimiter.yaml
---
domain: ratelimiter
descriptors:
  - key: remote_address
    rate_limit:
      unit: minute
      requests_per_unit: 1

  - key: generic_key
    value: default
    rate_limit:
      unit: second
      requests_per_unit: 500
```

envoy run in my localhost and made change to compose file to enable 8081 grpc port

From my understanding, api request hit `v1/generic/` would be limited by 500/s, and `v1` would be 1/min, but from the testing, I could get nearly 100% requests by vegeta

```
$ echo "GET http://127.0.0.1:18200/v1/sys/health" | vegeta attack -header "X-Vault-Token: $(cat ~/.vault-token)" -rate=1000 -duration=0 | tee results.bin | vegeta report
^CRequests      [total, rate]            7398, 991.69
Duration      [total, attack, wait]    7.489244538s, 7.460022s, 29.222538ms
Latencies     [mean, 50, 95, 99, max]  51.959881ms, 36.24044ms, 140.004647ms, 213.315832ms, 300.517854ms
Bytes In      [total, mean]            1946430, 263.10
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  98.54%
Status Codes  [code:count]             200:7290  429:108
Error Set:
429 Too Many Requests
```
and  ratelimit service logs

```
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="found rate limit: remote_address"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="starting cache lookup"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="starting cache lookup"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="looking up key: remote_address"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="found rate limit: remote_address"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="found rate limit: remote_address"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="looking up cache key: ratelimiter_remote_address_172.17.0.1_1542787020"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="looking up cache key: ratelimiter_remote_address_172.17.0.1_1542787020"
ratelimit_1_25f2c6251453 | time="2018-11-21T07:57:28Z" level=debug msg="cache key: ratelimiter_remote_address_172.17.0.1_1542787020 current: 1419"
```
